apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ vm_name }}-root-disk
  namespace: {{ namespace }}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    {% if node_selector %}
    {% for k, v in node_selector.items() %}
    cdi.kubevirt.io/storage.node.selector: "{{ k }}={{ v }}"
    {% endfor %}
    {% endif %}
spec:
  source:
    http:
      url: {{ image_url }}
  pvc:
    accessModes:
      - {{ access_mode }}
    {% if node_selector %}
    selector:
      matchLabels:
        {% for k, v in node_selector.items() %}
        {{ k }}: {{ v }}
        {% endfor %}
    {% endif %}
    storageClassName: {{ storage_class }}
    resources:
      requests:
        storage: {{ disk_size }}
