apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ nad_name }}
  namespace: {{ namespace }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "{{ nad_name }}",
      "type": "bridge",
      "bridge": "{{ bridge }}",
      "ipam": {{ ipam }}
    }'
