apiVersion: v1
kind: Secret
metadata:
  name: {{ vm_name }}-cloud-init
  namespace: {{ namespace }}
type: Opaque
stringData:
  userdata: |
    {% if cloud_init_content %}
    {{ cloud_init_content | indent(4) }}
    {% else %}
    #cloud-config
    user: {{ username }}
    password: '{{ password }}'
    chpasswd: { expire: False }
    ssh_pwauth: True
    sudo: ALL=(ALL) NOPASSWD:ALL
    write_files:
      - path: /etc/netplan/99-secondary-net.yaml
        owner: root:root
        permissions: '0644'
        content: |
          network:
            version: 2
            ethernets:
              enp2s0:
                dhcp4: true
                dhcp4-overrides:
                  use-routes: false
                optional: true
    runcmd:
      - netplan apply
    {% endif %}
