apiVersion: v1
kind: Secret
metadata:
  name: {{ vm_name }}-cloud-init
  namespace: {{ namespace }}
type: Opaque
stringData:
  userData: |
    {% if cloud_init_content %}
    {{ cloud_init_content | indent(4) }}
    {% endif %}
  {% if network_config %}
  networkData: |
    {{ network_config | to_yaml | indent(4) }}
  {% endif %}
